Fix compile error
Previous PR causes a compile error like
```
16:22:27  | ../git/src/ssl_key_handler.cpp:294:59: error: conversion from 'int64_t' {aka 'long long int'} to 'long int' may change value [-Werror=conversion]
16:22:27  |   294 |             ASN1_INTEGER_set(X509_get_serialNumber(x509), serial);
16:22:27  |       |                                                           ^~~~~~
16:22:27  | cc1plus: all warnings being treated as errors
```

This fixes it.

Signed-off-by: Myung Bae <myungbae@us.ibm.com>