Revert "FFDC: Collect current in-memory sessions for BMC dump (#510)"
bmcweb bump is failing. The failure is:
 In file included from ../git/http/http_server.hpp:23,
|                  from ../git/http/app.hpp:5,
|                  from ../git/src/webserver_main.cpp:4:
| ../git/include/persistent_data.hpp: In member function 'void
persistent_data::ConfigFile::writeCurrentSessionData()':
| ../git/include/persistent_data.hpp:228:35: error: no matching function
for call to
'nlohmann::json_abi_v3_11_2::basic_json<>::push_back(<brace-enclosed
initializer list>)'
|   228 |                 sessions.push_back({
|       |                 ~~~~~~~~~~~~~~~~~~^~
|   229 |                     {"unique_id", p.second->uniqueId},
|       |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
|   230 |                     {"username", p.second->username},
|       |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
|   231 |                     {"client_ip", p.second->clientIp},
|       |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
|   232 |                     {"client_id", p.second->clientId},
|       |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
|   233 |                 });
|       |                 ~~
| In file included from ../git/http/http_response.hpp:3,

510 can be resubmitted.

This reverts commit 9c8f72077191ec5632f43d0f172eaa81b9df925f.