Fix PCIeSlots RedfishValidator Error (#769)
Redfish Validator skips the validation on PCIeSlots due to this error.

```
1 exceptionResource errors in /redfish/v1/Chassis/chassis/PCIeSlots

ERROR - This complex object LinkId should be a dictionary or None, but it's of type int...
ERROR - Unable to gather property info for URI /redfish/v1/Chassis/chassis/PCIeSlots: AttributeError("'int' object has no attribute 'get'")
```

This change will enhance the code to avoid exceptionResource errors
and continue to examine PCIeSlots.

However, it will go back to previous errors like this.
```
26 err.Collection(Processor.Processor) errors in /redfish/v1/Chassis/chassis/PCIeSlots
26 failProp errors in /redfish/v1/Chassis/chassis/PCIeSlots
...
ERROR - Processors: Linked resource reports version Processor.v1_18_0.Processor not in Schema
```

This seems caused by the Processor schema definition issue and this
would be addressed separately.

```
python3 RedfishServiceValidator.py --auth Session -i https://${bmc}  --payload Single /redfish/v1/Systems/system/Processors
```

Signed-off-by: Myung Bae <myungbae@us.ibm.com>