Fix compiler error due to incorrect variable name
A previous PR #760 has an typo in using a wrong variable
and it causes the compiler error.

```
| In file included from ../../../../../../../../../ibm-bmcweb/redfish-core/lib/systems.hpp:27,
|                  from ../../../../../../../../../ibm-bmcweb/redfish-core/include/redfish.hpp:55,
|                  from ../../../../../../../../../ibm-bmcweb/src/webserver_main.cpp:21:
| ../../../../../../../../../ibm-bmcweb/redfish-core/lib/oem/ibm/system_attention_indicator.hpp: In lambda function:
| ../../../../../../../../../ibm-bmcweb/redfish-core/lib/oem/ibm/system_attention_indicator.hpp:62:67: error: 'ec' is not captured
|    62 |                     BMCWEB_LOG_ERROR << "DBUS response error " << ec.value();
|       |                                                                   ^~
| ../../../../../../../../../ibm-bmcweb/redfish-core/lib/oem/ibm/system_attention_indicator.hpp:56:34: note: the lambda has no capture-default
|    56 |             [aResp, propertyValue](const boost::system::error_code& ec1,
|       |                                  ^
| ../../../../../../../../../ibm-bmcweb/redfish-core/lib/oem/ibm/system_attention_indicator.hpp:44:58: note: 'const boost::system::error_code& ec' declared here
|    44 |          propertyValue](const boost::system::error_code& ec,
|       |                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
```

Tested:
- Compile pases

Signed-off-by: Myung Bae <myungbae@us.ibm.com>