Redfish : Add USB code update Enable/Disable (#813)(#913)(#916) Implement USB code update Enable/Disable. This is an OEM schema.
We can use "ibm-usb-code-update" option to enable/disable this feature.

Tested: Validator no error
First, we need to pick this commit:
[1] https://gerrit.openbmc-project.xyz/c/openbmc/service-config-manager/+/48780
or
[2] ibm-openbmc/service-config-manager#1

1. Get USB code update state
```
curl -k -H "X-Auth-Token: $token" -X GET https://${bmc}/redfish/v1/Managers/bmc
{
  "@odata.id": "/redfish/v1/Managers/bmc",
  "@odata.type": "#Manager.v1_11_0.Manager",

  ...

  "Oem": {
    "@odata.id": "/redfish/v1/Managers/bmc#/Oem",
    "@odata.type": "#OemManager.Oem",
    "IBM": {
      "@odata.id": "/redfish/v1/Managers/bmc#/Oem/IBM",
      "@odata.type": "#OemManager.IBM",
      "USBCodeUpdateEnabled": true
    },
    "OpenBmc": {
      "@odata.id": "/redfish/v1/Managers/bmc#/Oem/OpenBmc",
      "@odata.type": "#OemManager.OpenBmc",
      "Certificates": {
        "@odata.id": "/redfish/v1/Managers/bmc/Truststore/Certificates"
      }
    }
  },

  ...
```
2. Set disable USB code update
```
curl -k -H "X-Auth-Token: $token" -X PATCH https://${bmc}/redfish/v1/Managers/bmc -d '{"Oem":{"IBM":{"USBCodeUpdateEnabled": false}}}'

busctl get-property xyz.openbmc_project.Control.Service.Manager /xyz/openbmc_project/control/service/phosphor_2dusb_2dcode_2dupdate xyz.openbmc_project.Control.Service.Attributes Enabled
b false
```
3. Set enable USB code update
```
curl -k -H "X-Auth-Token: $token" -X PATCH https://${bmc}/redfish/v1/Managers/bmc -d '{"Oem":{"IBM":{"USBCodeUpdateEnabled": true}}}'

busctl get-property xyz.openbmc_project.Control.Service.Manager /xyz/openbmc_project/control/service/phosphor_2dusb_2dcode_2dupdate xyz.openbmc_project.Control.Service.Attributes Enabled
b true
```

Signed-off-by: George Liu <liuxiwei@ieisystem.com>
Signed-off-by: Abiola Asojo <abiola.asojo@ibm.com>

Enable IBM options by default
* Cleanup License, pass unit test

When redfish-license was enabled, which is what I am doing in the commit
above, this unit test fails. Make it pass.

Like we do upstream:
openbmc/bmcweb@7f3e84a
openbmc/bmcweb@8db8374

Signed-off-by: Gunnar Mills <gmills@us.ibm.com>
Signed-off-by: Abiola Asojo <abiola.asojo@ibm.com>

* Enable IBM options by default

Now CI tests these code paths.

Signed-off-by: Gunnar Mills <gmills@us.ibm.com>
Signed-off-by: Abiola Asojo <abiola.asojo@ibm.com>

Leave off USB code update if no backend (#916)
This appears what we had in 1020-1060.

Tested: Enable USB code update. Load on rainier with no backend. 200 rc
for manager resource.

Signed-off-by: Gunnar Mills <gmills@us.ibm.com>
Signed-off-by: Abiola Asojo <abiola.asojo@ibm.com>

Fix USB code update errors
Was seeing the following errors when building with:
https://github.ibm.com/openbmc/openbmc/pull/4649

```

bmcweb/redfish-core/lib/oem/ibm/usb_code_update.hpp:51:17: error: 'BMCWEB_LOG_ERRO' was not declared in this scope; did you mean 'BMCWEB_LOG_ERROR'?
|    51 |                 BMCWEB_LOG_ERRO("DBUS response error: {}", ec2);

redfish-core/lib/oem/ibm/usb_code_update.hpp:35:21: error: capture of variable 'redfish::usbCodeUpdateObjectPath' with non-automatic storage duration [-Werror]
|    35 |         [asyncResp, usbCodeUpdateObjectPath](

```

Tested: This builds with 4649.

Signed-off-by: Gunnar Mills <gmills@us.ibm.com>
Signed-off-by: Abiola Asojo <abiola.asojo@ibm.com>