Bail if controlMode is invalid
This error was introduced in
https://github.com/ibm-openbmc/bmcweb/pull/135

When buildtype=debug:
../lib/environment_metrics.hpp:354:52: error: 'powerCapEnable' may be used
uninitialized in this function [-Werror=maybe-uninitialized]

Add the return.
This is a legit potential bug.

Tested: bmcweb builds with buildtype=debug. Did not do any further testing.
Signed-off-by: Gunnar Mills <gmills@us.ibm.com>