introduce meson option to enable the HMC
Need to enable this by default in downstream so that the functions get
called and clang16 doesn't error out like this:

```
In file included from ../src/webserver_main.cpp:9:
../include/event_dbus_monitor.hpp:538:13: error: 'void crow::dbus_monitor::registerDumpUpdateSignal()' defined but not used [-Werror=unused-function]
  538 | static void registerDumpUpdateSignal()
      |             ^~~~~~~~~~~~~~~~~~~~~~~~
```

Signed-off-by: Andrew Geissler <geissonator@yahoo.com>